name: package_name
version: 0.0.1
description: << Description (not less than 60 characters) >>.
homepage: https://zamstation.com
repository: https://github.com/zamstation/package_name

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  zam_core: ^0.1.1

dev-dependencies:
  zam_test: ^0.0.2
