name: Dev Build

on:
  push:
    branches-ignore: ['**']
    # branches:
    #   - 'develop'
    #   - 'bugfix/**'
    #   - 'feature/**'
    #   - 'release/**'
    #   - 'hotfix/**'
    #   - 'support/**'
  pull_request:
    branches-ignore: ['**']
    # branches:
    #   - 'develop'
    #   - 'bugfix/**'
    #   - 'feature/**'
    #   - 'release/**'
    #   - 'hotfix/**'
    #   - 'support/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
